version: '3.8'

services:
  frontend:
    image: nginx:latest
    ports:
      - "8080:80" # Le port 80 du conteneur est accessible via le port 8080 sur la machine hôte
    volumes:
      - ./frontend:/usr/share/nginx/html # Dossier frontend monté pour servir les fichiers HTML/CSS/JS
      - ./logs/nginx:/var/log/nginx # Sauvegarde des journaux Nginx
    networks:
      - hackathon_network # Réseau partagé entre les services

  backend:
    build:
      context: ./backend # Dockerfile pour construire l'image backend
    ports:
      - "5000:5000" # Port 5000 exposé pour le backend
    depends_on:
      - db # Attente que la base de données démarre avant de lancer ce service
    volumes:
      - ./backend:/app # Code source monté pour le développement
    networks:
      - hackathon_network

  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root # Mot de passe root
      MYSQL_DATABASE: hackathon # Base de données créée au démarrage
    ports:
      - "5001:5001" # Port MySQL/MariaDB exposé
    volumes:
      - db_data:/var/lib/mysql # Données persistantes
    networks:
      - hackathon_network

volumes:
  db_data: # Volume pour stocker les données de la base de données

networks:
  hackathon_network: # Réseau pour connecter les services
