version: '3.8'

services:
  frontend:
    image: nginx:latest
    volumes:
      - ./frontend:/usr/share/nginx/html # Dossier frontend monté pour servir les fichiers HTML/CSS/JS
      - ./logs/nginx:/var/log/nginx # Sauvegarde des journaux Nginx
    network_mode: "host" # Mode hôte pour le réseau

  backend:
    build:
      context: ./backend # Dockerfile pour construire l'image backend
    depends_on:
      - db # Attente que la base de données démarre avant de lancer ce service
    volumes:
      - ./backend:/app # Code source monté pour le développement
    network_mode: "host" # Mode hôte pour le réseau

  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root # Mot de passe root
      MYSQL_DATABASE: hackathon # Base de données créée au démarrage
    volumes:
      - db_data:/var/lib/mysql # Données persistantes
    network_mode: "host" # Mode hôte pour le réseau

volumes:
  db_data: # Volume pour stocker les données de la base de données
