services:
  backend:
    build:
      context: ./backend
    ports:
      - "${PORT}:3000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
    env_file: # Ajout ici
      - .env

  db:
    image: mariadb
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    env_file: # Ajout ici aussi
      - .env

volumes:
  db_data:
