# Utiliser une image Node.js officielle
FROM node:14

# Définir le répertoire de travail
WORKDIR /app

# Copier uniquement les fichiers nécessaires pour npm install
COPY package*.json ./

# Installer les dépendances
RUN npm install

# Copier le reste des fichiers du projet
COPY . .

# Exposer le port 3000
EXPOSE 3000

# Démarrer l'application
CMD ["npm", "start"]
